import pycurl
import json
import random
import time

prompts = [ "What is the meaning of life?",
"What is the nature of the universe?",
"What is the nature of consciousness?",
"How do we know what we know?",
"What is the nature of reality?",
"What is the nature of time?",
"What is the nature of space?",
"What is the nature of matter?",
"What is the nature of energy?",
"What is the nature of the mind?",
"What is the nature of the self?",
"What is the nature of the soul?",
"What is the nature of language?",
"What is the nature of consciousness?",
"What is the nature of the mind-body problem?",
"What is the nature of free will?",
"What is the nature of moral responsibility?",
"What is the nature of morality?",
"What is the nature of justice?",
"What is the nature of law?",
"What is the nature of politics?",
"What is the nature of government?",
"What is the nature of democracy?",
"What is the nature of power?",
"What is the nature of authority?",
"What is the nature of capitalism?",
"What is the nature of socialism?",
"What is the nature of communism?",
"What is the nature of economic systems?",
"What is the nature of wealth?",
"What is the nature of poverty?",
"What is the nature of inequality?",
"What is the nature of social systems?",
"What is the nature of society?",
"What is the nature of culture?",
"What is the nature of art?",
"What is the nature of beauty?",
"What is the nature of aesthetics?",
"What is the nature of music?",
"What is the nature of literature?",
"What is the nature of film?",
"What is the nature of television?",
"What is the nature of video games?",
"What is the nature of sports?",
"What is the nature of education?",
"What is the nature of learning?",
"What is the nature of intelligence?",
"What is the nature of creativity?",
"What is the nature of innovation?",
"What is the nature of technology?",
"What is the nature of science?",
"What is the nature of mathematics?",
"What is the nature of logic?",
"What is the nature of reasoning?",
"What is the nature of philosophy?",
"What is the nature of theology?",
"What is the nature of religion?",
"What is the nature of faith?",
"What is the nature of spirituality?",
"What is the nature of belief?",
"What is the nature of skepticism?",
"What is the nature of doubt?",
"What is the nature of truth?",
"What is the nature of knowledge?",
"What is the nature of wisdom?",
"What is the nature of understanding?",
"What is the nature of learning?",
"What is the nature of memory?",
"What is the nature of perception?",
"What is the nature of attention?",
"What is the nature of emotion?",
"What is the nature of love?",
"What is the nature of happiness?",
"What is the nature of sadness?",
"What is the nature of anger?",
"What is the nature of fear?",
"What is the nature of anxiety?",
"What is the nature of stress?",
"What is the nature of depression?",
"What is the nature of mental health?",
"What is the nature of personality?",
"What is the nature of character?",
"What is the nature of leadership?",
"What is the nature of teamwork?",
"What is the nature of collaboration?",
"What is the nature of communication?",
"What is the nature of relationships?",
"What is the nature of love?",
"What is the nature of friendship?",
"What is the nature of family?",
"What is the nature of parenting?",
"What is the nature of childhood?",
"What is the nature of adolescence?",
"What is the nature of adulthood?",
"What is the nature of aging?",
"What is the nature of death?",
"What is the nature of the afterlife?",
"What is the nature of spirituality?",
"What is the nature of the human experience?",
"What is the nature of quantum physics?",
"What is the nature of the big bang theory?",
"What is the nature of the universe's expansion?",
"What is the nature of black holes?",
"What is the nature of dark matter and dark energy?",
"What is the nature of gravitational waves?",
"What is the nature of string theory?",
"What is the nature of the multiverse?",
"What is the nature of time travel?",
"What is the nature of parallel universes?",
"What is the nature of artificial intelligence?",
"What is the nature of machine learning?",
"What is the nature of neural networks?",
"What is the nature of natural language processing?",
"What is the nature of robotics?",
"What is the nature of self-driving cars?",
"What is the nature of virtual reality?",
"What is the nature of augmented reality?",
"What is the nature of the internet?",
"What is the nature of the World Wide Web?",
"What is the nature of social media?",
"What is the nature of online privacy?",
"What is the nature of cybersecurity?",
"What is the nature of blockchain?",
"What is the nature of cryptocurrency?",
"What is the nature of data science?",
"What is the nature of big data?",
"What is the nature of data analytics?",
"What is the nature of data visualization?",
"What is the nature of machine learning?",
"What is the nature of data mining?",
"What is the nature of the cloud?",
"What is the nature of cloud computing?",
"What is the nature of cloud storage?",
"What is the nature of the cloud infrastructure?",
"What is the nature of distributed systems?",
"What is the nature of microservices?",
"What is the nature of containers?",
"What is the nature of Kubernetes?",
"What is the nature of serverless computing?",
"What is the nature of IoT?",
"What is the nature of smart homes?",
"What is the nature of smart cities?",
"What is the nature of connected devices?",
"What is the nature of the Internet of Things?",
"What is the nature of the connected car?",
"What is the nature of smart wearables?",
"What is the nature of smart home appliances?",
"What is the nature of smart factories?",
"What is the nature of the industrial internet of things?",
"What is the nature of 5G?",
"What is the nature of wireless technology?",
"What is the nature of mobile computing?",
"What is the nature of mobile app development?",
"What is the nature of mobile design?",
"What is the nature of mobile user experience?",
"What is the nature of mobile marketing?",
"What is the nature of mobile advertising?",
"What is the nature of mobile payment systems?",
"What is the nature of mobile commerce?",
"What is the nature of mobile security?",
"What is the nature of mobile privacy?",
"What is the nature of mobile device management?",
"What is the nature of mobile device security?",
"What is the nature of mobile device encryption?",
"What is the nature of mobile device forensics?",
"What is the nature of mobile device repair?",
"What is the nature of mobile device deployment?",
"What is the nature of mobile device onboarding?",
"What is the nature of mobile device maintenance?",
"What is the nature of mobile device updates?",
"What is the nature of mobile device provisioning?",
"What is the nature of mobile device licensing?",
"What is the nature of mobile device support?",
"What is the nature of mobile device troubleshooting?",
"What is the nature of mobile device service?",
"What is the nature of mobile device recycling?",
"What is the nature of mobile device disposal?",
"What is the nature of mobile device trade-in?",
"What is the nature of mobile device trade-up?",
"What is the nature of mobile device financing?",
"What is the nature of mobile device leasing?",
"What is the nature of mobile device insurance?",
"What is the nature of mobile device warranties?",
"What is the nature of mobile device protection plans?",
"What is the nature of mobile device accessories?",
"What is the nature of mobile device cases?",
"What is the nature of mobile device screen protectors?",
"What is the nature of mobile device chargers?",
"What is the nature of mobile device cables?",
"What is the nature of mobile device docks?",
"What is the nature of mobile device mounts?",
"What is the nature of mobile device stands?",
"What is the nature of mobile device speakers?",
"What is the nature of mobile device headphones?",
"What is the nature of mobile device earbuds?",
"What is the nature of mobile device microphones?",
"What is the nature of mobile device cameras?",
"What is the nature of mobile device lenses?",
"What is the definition of artificial intelligence?",
"What is the purpose of machine learning?",
"What are the benefits of neural networks?",
"What are the challenges of natural language processing?",
"How does robotics work?",
"What is the future of self-driving cars?",
"What is the potential of virtual reality?",
"How does augmented reality differ from virtual reality?",
"What is the structure of the internet?",
"What is the history of the World Wide Web?",
"How do social media platforms operate?",
"What are the concerns surrounding online privacy?",
"What are the types of cybersecurity threats?",
"What is the function of blockchain technology?",
"What is the role of cryptocurrency in the economy?",
"What is the process of data science?",
"How is big data analyzed?",
"What are the techniques of data analytics?",
"How is data visualized?",
"What is the purpose of machine learning?",
"What is the process of data mining?",
"What is the concept of the cloud?",
"How does cloud computing work?",
"What are the benefits of cloud storage?",
"What is the structure of cloud infrastructure?",
"What is the concept of distributed systems?",
"What are the characteristics of microservices?",
"How do containers work?",
"What is the function of Kubernetes?",
"What is the concept of serverless computing?",
"What is the definition of the IoT?",
"What are the capabilities of smart homes?",
"What are the benefits of smart cities?",
"What are the types of connected devices?",
"What is the scope of the Internet of Things?",
"What are the capabilities of the connected car?",
"What are the types of smart wearables?",
"What are the features of smart home appliances?",
"What is the concept of smart factories?",
"What is the definition of the industrial internet of things?",
"What are the capabilities of 5G?",
"What are the principles of wireless technology?",
"What is the concept of mobile computing?",
"What is the process of mobile app development?",
"What are the principles of mobile design?",
"What is the concept of mobile user experience?",
"What is the role of mobile marketing?",
"What is the purpose of mobile advertising?",
"What are the types of mobile payment systems?",
"What is the concept of mobile commerce?",
"What are the concerns of mobile security?",
"What are the issues surrounding mobile privacy?",
"What is the function of mobile device management?",
"What are the principles of mobile device security?",
"What is the process of mobile device encryption?",
"What is the purpose of mobile device forensics?",
"What is the process of mobile device repair?",
"What is the concept of mobile device deployment?",
"What is the process of mobile device onboarding?",
"What is the role of mobile device maintenance?",
"What is the process of mobile device updates?",
"What is the concept of mobile device provisioning?",
"What is the process of mobile device licensing?",
"What is the role of mobile device support?",
"What is the process of mobile device troubleshooting?",
"What is the concept of mobile device service?",
"What is the process of mobile device recycling?",
"What is the history of Turkey?",
"What are the major cultural influences in Turkey?",
"What is the political system of Turkey?",
"What are the major economic sectors in Turkey?",
"What are the natural resources of Turkey?",
"What is the climate of Turkey?",
"What are the major cities in Turkey?",
"What is the demographics of Turkey?",
"What is the education system in Turkey?",
"What are the major religions in Turkey?",
"What is the role of Turkey in international relations?",
"What are the major issues facing Turkey today?",
"What is the history of the Turkish language?",
"What are the major cultural events in Turkey?",
"What is the role of the arts in Turkey?",
"What are the major tourist attractions in Turkey?",
"What is the role of sports in Turkey?",
"What is the role of the media in Turkey?",
"What is the role of the military in Turkey?",
"What is the history of Turkish cuisine?",
"What are the major holidays in Turkey?",
"What is the role of the family in Turkish culture?",
"What is the role of gender in Turkish society?",
"What is the history of Turkish literature?",
"What are the major influences on Turkish music?",
"What are the traditional and modern forms of Turkish dance?",
"What is the role of art and architecture in Turkish culture?",
"What is the history of Turkish cinema?",
"What is the history of Turkish television?",
"What is the role of fashion in Turkish culture?",
"What is the history of Turkish sports?",
"What are the major sporting events in Turkey?",
"What are the major Turkish sports teams and athletes?",
"What is the role of education in Turkish society?",
"What are the major universities in Turkey?",
"What is the role of science and technology in Turkey?",
"What is the history of Turkish science and technology?",
"What are the major research institutions in Turkey?",
"What are the major contributions of Turkey to the scientific community?",
"What is the history of Turkish medicine?",
"What are the major healthcare issues facing Turkey today?",
"What is the history of Turkish agriculture?",
"What are the major agricultural products of Turkey?",
"What is the history of Turkish industry?",
"What are the major industries in Turkey today?",
"What is the history of Turkish trade and commerce?",
"What are the major trading partners of Turkey?",
"What is the history of Turkish transportation?",
"What are the major transportation systems in Turkey?",
"What is the history of Turkish energy production?",
"What are the major energy sources in Turkey?",
"What is the history of Turkish environmental policy?",
"What are the major environmental issues facing Turkey today?",
"What is the history of Turkish politics?",
"What are the major political parties in Turkey?",
"What is the history of film?",
"What are the major film genres?",
"What are the major film studios?",
"What are the major film festivals?",
"What are the influential film directors?",
"What are the influential film actors and actresses?",
"What are the influential film writers and screenplays?",
"What are the influential film producers?",
"What are the influential film cinematographers?",
"What are the influential film editors?",
"What are the influential film production designers?",
"What are the influential film composers?",
"What are the influential film sound designers?",
"What are the influential film visual effects artists?",
"What are the influential film costume designers?",
"What are the influential film makeup artists?",
"What are the influential film production companies?",
"What are the influential film distribution companies?",
"What are the influential film exhibition companies?",
"What are the influential film marketing and advertising companies?",
"What are the influential film critics and journalism outlets?",
"What are the influential film history and theory scholars?",
"What are the influential film preservation and archival organizations?",
"What are the influential film industry trade organizations?",
"What are the influential film award shows and ceremonies?",
"What are the influential film societies and clubs?",
"What are the influential film education and training programs?",
"What are the influential film research and development organizations?",
"What are the influential film financing and funding organizations?",
"What are the influential film business and legal organizations?",
"What are the influential film technology companies and startups?",
"What are the influential film software and hardware companies?",
"What are the influential film database and information services?",
"What are the influential film streaming and distribution platforms?",
"What are the influential film social media and online communities?",
"What are the influential film mobile and app development companies?",
"What are the influential film virtual and augmented reality companies?",
"What are the influential film content licensing and sales companies?",
"What are the influential film merchandising and consumer products companies?",
"What are the influential film licensing and rights management companies?",
"What are the major film techniques and technologies?",
"What are the major film formats and standards?",
"What are the major film production and post-production processes?",
"What are the major film distribution and exhibition strategies?",
"What are the major film business and financial models?",
"What are the major film marketing and advertising strategies?",
"What are the major film industry trends and forecasts?",
"What are the major film industry challenges and opportunities?",
"What are the major film industry laws and regulations?",
"What are the major film industry ethical and social issues?",
"What are the major film industry diversity and inclusion initiatives?",
"What are the major film industry philanthropy and social impact programs?",
"What are the major film industry sustainability and environmental initiatives?",
"What are the major film industry innovation and disruption initiatives?",
"What are the major film industry collaborations and partnerships?",
"What are the major film industry conferences and events?",
"What are the major film industry trade publications and media outlets?",
"What are the major film industry research and market intelligence organizations?",
"What are the major film industry professional development and training programs?",
"What are the major film industry networking and community building organizations?",
"What are the major film industry mentorship and coaching programs?",
"What are the major film industry internship and job placement programs?",
"What are the major film industry job boards and career resources?",
"What are the major film industry salary and benefits surveys?",
"What are the major film industry job market trends and forecasts?",
"What are the major film industry job skills and requirements?",
"What are the major film industry job titles and roles?",
"What are the major film industry job industries and sectors?",
"What are the major film industry job career paths and advancement opportunities?",
"What are the major film industry job professional associations and membership organizations?",
"What are the major film industry job certification and accreditation programs?",
"What are the major film industry job education and training programs?",
"What are the major film industry job networking and community building events?",
"What are the major film industry job workshops and seminars?",
"What are the major film industry job online and distance learning programs?",
"What are the major film industry job mentorship and coaching programs?",
"What are the major film industry job internships and job placements?",
"What are the major film industry job job boards and career resources?",
"What are the major film industry job salary and benefits surveys?",
"What are the major film industry job market trends and forecasts?",
"What are the major film industry job skills and requirements?",
"What are the major film industry job titles and roles?",
"What are the major film industry job industries and sectors?",
"What are the major film industry job career paths and advancement opportunities?",
"What are the major film industry job professional associations and membership organizations?",
"What are the major film industry job certification and accreditation programs?",
"What are the major film industry job education and training programs?",
"What are the major film industry job networking and community building events?",
"What are the major film industry job workshops and seminars?",
"What are the major film industry job online and distance learning programs?",
"What are the major film industry job mentorship and coaching programs?",
"What are the major film industry job internships and job placements?",
"What are the major film industry job job boards and career resources?",
"What are the major film industry job salary and benefits surveys?",
"What are the major film industry job market trends and forecasts?",
"What are the major film industry job skills and requirements?",
"What are the major film industry job titles and roles?",
"What are the major film industry job industries and sectors?",
"What are the major film industry job career paths and advancement opportunities?",
]

c = pycurl.Curl()

# Set the URL to send the request to
c.setopt(c.URL, 'TRIGER-URL-FOR-EVENT-HANDLER-FUNCTION')

# Set the request method to POST
c.setopt(c.POST, 1)

# Set the request headers
c.setopt(c.HTTPHEADER, ["Content-Type: application/json", ])


for x in range(1000):
    
    # Set the request body
    request_data = {'event': {
        
        'text' : prompts[random.randint(0, 400)]
       }}
    c.setopt(c.POSTFIELDS, json.dumps(request_data))
    
    time.sleep(0.7);

    # Perform the request
    c.perform()
        
# Close the connection
c.close()
